---
###########################################################################
# Test playbook for infoblox-client debug
#
# This playbook runs through some standard Infoblox-client commands, like:
#
# - nios_lookup
# - nios_next_network
# - nios_network (one that should give error)
#
###########################################################################
- hosts: nios
  connection: local
  name: ALLOCATE INFOBLOX SUBNET

  vars:
    nios_provider:
      host: "{{ inventory_hostname }}"
      username: "{{ lookup('env', 'ANSIBLE_NET_USERNAME') }}"
      password: "{{ lookup('env', 'ANSIBLE_NET_PASSWORD') }}"
      ssl_verify: false
    application: "mytestapp"
    random_number: "{{ 1000 | random(start=1) }}"
    bd_name: "bd_{{ application }}_{{ random_number }}"
    bonus_code: true

  tasks:
    - name: Lookup function - nios_lookup function
      # Perform nios_lookup function on Infoblox network container
      set_fact:
        network_container_result: "{{ lookup('infoblox.nios_modules.nios_lookup', 'networkcontainer', filter={'comment': application }, return_fields=['extattrs', 'network', 'comment'], provider=nios_provider, wantlist=True) }}"

    - name: Debug - Show network container result
      debug:
        var: network_container_result

    - name: Lookup function - nios_next_network function
      # Perform nios_next_network to obtain next available /29 network from retrieved network container
      set_fact:
        networkaddr: "{{ lookup('infoblox.nios_modules.nios_next_network', network_container_result[0].network, cidr=29, provider=nios_provider) }}"

    - name: Create new network - nios_network function
      # Create new network through nios_network function with /29 network retrieved from nios_next_network
      infoblox.nios_modules.nios_network:
        network: "{{ networkaddr[0] }}"
        comment: "{{ bd_name }}"
        template: "network29"
        state: present
        provider: "{{ nios_provider }}"

    - name: Debug - Show created Infoblox network
      debug:
        msg: "Created network: {{ bd_name }} with IP subnet {{ networkaddr[0] }} on {{ inventory_hostname }}" 

    - name: Bonus code
      # Runs bonus testing code attempting six ansible/python dependency - Suspecting problem with six dependency - might be delirious from cold/flu
      block:

        - name: Create DNS host - nios_host_record function to uses six
          infoblox.nios_modules.nios_host_record:
            name: "host{{ random_number }}.ansible.com"
            ipv4:
              - address: 192.168.10.1
            state: present
            provider: "{{ nios_provider }}"

        - name: Create DNS txt record - nios_text_record function that does NOT use six
          infoblox.nios_modules.nios_txt_record:
            name: text{{ random_number }}.record.com
            text: mytext
            state: present

      when: bonus_code